In [2]:
import numpy as np
                                                                                                                            

In [11]:
ar1 = np.array([2,3,1,4,5,6])
ar1

array([2, 3, 1, 4, 5, 6])

In [12]:
type(ar1)

numpy.ndarray

In [13]:
ar2 = np.array([[1,2,3],[3,4,5]])
ar2
type(ar2)

numpy.ndarray

In [18]:
ar3 = np.zeros((3,4))
ar3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
ar = np.ones((3,4))
ar

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
ar = np.identity(5)
ar

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
ar = np.arange(10)
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
ar=np.arange(2,10)
ar

array([2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
ar = np.arange(1,30,3)
ar

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28])

In [34]:
ar = np.linspace(10,20,20)

ar.shape
ar

array([10.        , 10.52631579, 11.05263158, 11.57894737, 12.10526316,
       12.63157895, 13.15789474, 13.68421053, 14.21052632, 14.73684211,
       15.26315789, 15.78947368, 16.31578947, 16.84210526, 17.36842105,
       17.89473684, 18.42105263, 18.94736842, 19.47368421, 20.        ])

In [31]:
ar = np.linspace(1,4,4)
ar

array([1., 2., 3., 4.])

In [32]:
ar1 = ar.copy()
ar1

array([1., 2., 3., 4.])

In [43]:
ar =np.array([[[1,2,3],[1,3,4]],[[1,2,3],[2,3,4]]])
ar


array([[[1, 2, 3],
        [1, 3, 4]],

       [[1, 2, 3],
        [2, 3, 4]]])

In [44]:
ar.shape

(2, 2, 3)

In [45]:
ar.ndim

3

In [46]:
ar1.ndim


1

In [49]:
ar.size

12

In [51]:
ar.itemsize

8

In [52]:
ar1.itemsize

8

In [53]:
ar


array([[[1, 2, 3],
        [1, 3, 4]],

       [[1, 2, 3],
        [2, 3, 4]]])

In [54]:
ar.itemsize


8

In [55]:
ar.dtype

dtype('int64')

In [57]:
list = range(1,100)
ar10= np.arange(100)


In [58]:
import sys


In [63]:
print(sys.getsizeof(99)*len(list))

2772


In [64]:
print(ar10.itemsize*ar10.size)


800


In [65]:
print(ar10.size)

100


In [66]:
print(ar10.itemsize)


8


In [3]:
import time

In [5]:
ar1 = range(100000)
ar2 = range(100000,200000)
start_time = time.time()
c = [(ar1,ar2) for x,y in zip(ar1,ar2)]
print(time.time()-start_time)

0.058713674545288086


In [ ]:
ar1 = range(200000000)
ar2 = range(100000000,300000000)
start_time = time.time()
c = [(ar1,ar2) for x,y in zip(ar1,ar2)]
print(time.time()-start_time)

In [ ]:
a = np.arange(1000000000)
b = np.arange(1000000000,2000000000)
start_time = time.time()
c = a+b
print(time.time()-start_time)

In [11]:
import numpy as np
arr2 = np.arange(24).reshape(2,12)

In [12]:
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [14]:
arr2[1]

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [18]:
arr2[:1]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [19]:
arr2[:,2]

array([ 2, 14])

In [20]:
arr2[:,5]

array([ 5, 17])

In [21]:
arr2[:2,]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [22]:
arr2[:,5:7]

array([[ 5,  6],
       [17, 18]])

In [23]:
arr2[:,5:9]

array([[ 5,  6,  7,  8],
       [17, 18, 19, 20]])

In [31]:
arr2[0:1,4:9]

array([[4, 5, 6, 7, 8]])

In [32]:
for i in arr2:
    print(i)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[12 13 14 15 16 17 18 19 20 21 22 23]


In [34]:
for i in np.nditer(arr2):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


In [35]:
ar1 = np.array([1,2,4,4,7,5])
ar2 = np.array([3,4,5,6,7,5])for i in np.nditer(arr2):

    print(i)



In [36]:
ar1-ar2

array([-2, -2, -1, -2,  0,  0])

In [37]:
ar1*ar2

array([ 3,  8, 20, 24, 49, 25])

In [39]:
ar1*2

array([ 2,  4,  8,  8, 14, 10])

In [41]:
ar2**2

array([ 9, 16, 25, 36, 49, 25])

In [42]:
ar1>3

array([False, False,  True,  True,  True,  True])

In [43]:
arr1 = np.arange(8).reshape(2,4)
arr2 = np.arange(8,16).reshape(4,2)


In [44]:
arr1.dot(arr2)

array([[ 76,  82],
       [252, 274]])

In [45]:
arr1.max()

7

In [46]:
arr2.max()

15

In [47]:
arr2.min()

8

In [48]:
arr2.min

<function ndarray.min>

In [49]:
ar2 = np.reshape(6,4)

ValueError: cannot reshape array of size 1 into shape (4,)

In [50]:
ar3 = np.arange(24).reshape(6,4)

In [51]:
ar3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [52]:
ar3.min(axis=0)

array([0, 1, 2, 3])

In [53]:
ar3.max(axis=1)


array([ 3,  7, 11, 15, 19, 23])

In [54]:
ar3.min(axis=0)

array([0, 1, 2, 3])

In [55]:
ar3.max(axis=1)

array([ 3,  7, 11, 15, 19, 23])

In [56]:
ar3.min(axis=1)

array([ 0,  4,  8, 12, 16, 20])

In [57]:
ar3.max(axis=0)

array([20, 21, 22, 23])

In [59]:


ar3.mean()

11.5

In [60]:
ar3.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [61]:
ar3.std()

6.922186552431729

In [62]:
ar3.var()

47.916666666666664

In [63]:
np.median(ar3)

11.5

In [64]:
np.mean(ar3)

11.5

In [65]:
np.sin(ar3)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021],
       [-0.53657292,  0.42016704,  0.99060736,  0.65028784],
       [-0.28790332, -0.96139749, -0.75098725,  0.14987721],
       [ 0.91294525,  0.83665564, -0.00885131, -0.8462204 ]])

In [66]:
np.exp(np.sin(ar3))

array([[1.        , 2.31977682, 2.48257773, 1.15156284],
       [0.46916419, 0.383305  , 0.75622563, 1.9289708 ],
       [2.68950792, 1.51001334, 0.58040966, 0.36788304],
       [0.5847488 , 1.5222158 , 2.69286951, 1.91609228],
       [0.74983409, 0.38235817, 0.47190044, 1.16169159],
       [2.49165027, 2.30863315, 0.99118775, 0.42903344]])

In [67]:
np.sin(np.exp(ar3))

array([[ 0.84147098,  0.41078129,  0.89385495,  0.94447101],
       [-0.92876794, -0.68769141,  0.96486625, -0.21561571],
       [ 0.40176297, -0.79346054, -0.68870432,  0.99518943],
       [ 0.99176942,  0.98431229,  0.50140514,  0.98876265],
       [ 0.51336302,  0.732754  , -0.81440203,  0.29279934],
       [ 0.40068235,  0.87743083,  0.09709812, -0.42890502]])

In [69]:
ar2.ndim

1

In [70]:
ar3.ndim


2

In [71]:
ar3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [72]:
ar3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [73]:
ar3.transpose()

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

In [74]:
    ar3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [75]:
ar1

array([1, 2, 4, 4, 7, 5])

In [76]:
ar3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [77]:

ar4 = ar3.transpose()


In [78]:
ar4

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

In [88]:
ar5= ar4.reshape(6,4)

In [89]:
np.vstack((ar3,ar5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [ 0,  4,  8, 12],
       [16, 20,  1,  5],
       [ 9, 13, 17, 21],
       [ 2,  6, 10, 14],
       [18, 22,  3,  7],
       [11, 15, 19, 23]])

In [87]:
ar4

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

In [90]:
ar5

array([[ 0,  4,  8, 12],
       [16, 20,  1,  5],
       [ 9, 13, 17, 21],
       [ 2,  6, 10, 14],
       [18, 22,  3,  7],
       [11, 15, 19, 23]])

In [91]:
ar5[ar5>14]

array([16, 20, 17, 21, 18, 22, 15, 19, 23])

In [91]:
ar5[ar5>14]

array([16, 20, 17, 21, 18, 22, 15, 19, 23])

In [91]:
ar5[ar5>14]

array([16, 20, 17, 21, 18, 22, 15, 19, 23])

In [96]:
ar5[(ar5>12) & (ar5%2==0)] = 0

In [97]:
ar5

array([[ 0,  4,  8, 12],
       [ 0,  0,  1,  5],
       [ 9, 13, 17, 21],
       [ 2,  6, 10,  0],
       [ 0,  0,  3,  7],
       [11, 15, 19, 23]])

In [101]:
ar6 = np.arange(0,10).reshape(2,5)
ar7 = np.arange(10,20).reshape(5,2)
print(ar6,ar7)

[[0 1 2 3 4]
 [5 6 7 8 9]] [[10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [103]:
np.random.random()

0.04637607415671785

In [107]:
np.random.seed(1)
np.random.random()

0.417022004702574

In [109]:
np.random.uniform()

0.00011437481734488664

In [110]:
np.random.uniform(1,100,10).reshape(2,5)

array([[30.93092469, 15.52883319, 10.14152088, 19.43976093, 35.21051198],
       [40.27997995, 54.34285667, 42.50025693, 68.83673054, 21.24077272]])

In [113]:
a = np.random.randint(1,10,11)

In [114]:
a

array([1, 7, 8, 7, 2, 1, 2, 9, 9, 4, 9])

In [115]:
np.max(a)

9

In [116]:
np.min(a)

1

In [118]:
a[np.argmax(a)]

9

In [119]:
a[a%2==1]=-1

In [120]:
a

array([-1, -1,  8, -1,  2, -1,  2, -1, -1,  4, -1])

In [123]:
x = np.where(a%2 ==1,-5,a)
x

array([-5, -5,  8, -5,  2, -5,  2, -5, -5,  4, -5])

In [140]:
a=np.random.randint(1,50,10)

In [139]:
a = np.sort(ar5)
a

array([[ 0,  4,  8, 12],
       [ 0,  0,  1,  5],
       [ 9, 13, 17, 21],
       [ 0,  2,  6, 10],
       [ 0,  0,  3,  7],
       [11, 15, 19, 23]])

In [141]:
a

array([24, 16, 48, 24, 26,  8, 29, 11, 47, 33])

In [142]:
np.sort(a)

array([ 8, 11, 16, 24, 24, 26, 29, 33, 47, 48])

In [143]:
b = np.sort(a)

In [144]:
b

array([ 8, 11, 16, 24, 24, 26, 29, 33, 47, 48])

In [145]:
np.percentile(a,50)

25.0

In [146]:
np.percentile(a,70)


30.2

In [147]:
np.percentile(a,100)


48.0